# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) Python Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._models import DotFish
from ._models import DotFishMarket
from ._models import DotSalmon
from ._models import Error
from ._models import Fish
from ._models import MyBaseHelperType
from ._models import MyBaseType
from ._models import MyDerivedType
from ._models import array_wrapper
from ._models import basic
from ._models import boolean_wrapper
from ._models import byte_wrapper
from ._models import cat
from ._models import cookiecuttershark
from ._models import date_wrapper
from ._models import datetime_wrapper
from ._models import datetimerfc1123_wrapper
from ._models import dictionary_wrapper
from ._models import dog
from ._models import double_wrapper
from ._models import duration_wrapper
from ._models import float_wrapper
from ._models import goblinshark
from ._models import int_wrapper
from ._models import long_wrapper
from ._models import pet
from ._models import readonly_obj
from ._models import salmon
from ._models import sawshark
from ._models import shark
from ._models import siamese
from ._models import smart_salmon
from ._models import string_wrapper

from ._enums import CMYKColors
from ._enums import GoblinSharkColor
from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "DotFish",
    "DotFishMarket",
    "DotSalmon",
    "Error",
    "Fish",
    "MyBaseHelperType",
    "MyBaseType",
    "MyDerivedType",
    "array_wrapper",
    "basic",
    "boolean_wrapper",
    "byte_wrapper",
    "cat",
    "cookiecuttershark",
    "date_wrapper",
    "datetime_wrapper",
    "datetimerfc1123_wrapper",
    "dictionary_wrapper",
    "dog",
    "double_wrapper",
    "duration_wrapper",
    "float_wrapper",
    "goblinshark",
    "int_wrapper",
    "long_wrapper",
    "pet",
    "readonly_obj",
    "salmon",
    "sawshark",
    "shark",
    "siamese",
    "smart_salmon",
    "string_wrapper",
    "CMYKColors",
    "GoblinSharkColor",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
