name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install -g pnpm
        name: Install PNPM

      - run: pnpm install
        name: Install dependencies

      - run: pnpm check-version-mismatch
        name: Check dependencies are consitent

      - run: pnpm run build
        name: Build

      - run: ls ./packages/cadl-ranch-specs/node_modules/.bin
        name: Test LS

      - run: pnpm run validate-scenarios --debug
        name: Validate Scenarios

      - run: pnpm run validate-mock-apis --debug
        name: Validate mock apis

      - run: pnpm run generate-scenarios-summary --debug
        name: Generate scenario summary

      - run: pnpm run check-format
        name: Check formatting

      - run: git status --porcelain 2>/dev/null | wc -l
        name: Check not out of date generated files
